### ISSUE TITLE
Passing arguments to edit_config

### ISSUE THREAD

**Issue by NikosGkotsis** [vkosuri/robotframework-ncclient#5]
Hello,

There was an issue with the passing of arguments in edit_config which resulted to failures when trying to write on running configuration datastore.
I have made some changes to a new branch but i do not have rights to push my changes.
Can you please check the permissions?

Thanks
Nikos

**Comment by vkosuri** [comment]
@NikosGkotsis Thanks using this, I don't how you are doing, You can make fork of this repository and submit pull request. Some useful links are here.

1. https://help.github.com/articles/fork-a-repo/
2. https://help.github.com/articles/creating-a-pull-request/

**Comment by vkosuri** [comment]
@NikosGkotsis Thank you very much for you PR https://github.com/vkosuri/robotframework-ncclient/pull/6
